name: sk-rancho
region: fra
services:
  - name: web
    github:
      repo: 2112kraken/Centr-plus
      branch: main
      deploy_on_push: true
    source_dir: /
    http_port: 3000
    instance_count: 2
    instance_size_slug: professional-xs
    auto_deploy: true
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
      - domain: sk-rancho.com
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: CLERK_SECRET_KEY
        scope: RUN_TIME
        value: ${clerk.SECRET_KEY}
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        scope: RUN_TIME
        value: ${clerk.PUBLISHABLE_KEY}
      - key: DEFAULT_LOCALE
        scope: RUN_TIME
        value: uk
      - key: SUPPORTED_LOCALES
        scope: RUN_TIME
        value: uk,en
      - key: SKIP_ENV_VALIDATION
        scope: BUILD_TIME
        value: "true"
      - key: SITE_URL
        scope: RUN_TIME
        value: "https://sk-rancho.com"
    alert_policy:
      rule: DEPLOYMENT_FAILED
      disabled: false

  - name: api
    github:
      repo: 2112kraken/Centr-plus
      branch: main
      deploy_on_push: true
    source_dir: /apps/api
    http_port: 3001
    instance_count: 2
    instance_size_slug: professional-xs
    auto_deploy: true
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /api
      - domain: api.sk-rancho.com
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: BINOTEL_API_KEY
        scope: RUN_TIME
        value: ${binotel.API_KEY}
      - key: BINOTEL_SECRET
        scope: RUN_TIME
        value: ${binotel.SECRET}
      - key: BINOTEL_WIDGET_ID
        scope: RUN_TIME
        value: ${binotel.WIDGET_ID}
      - key: DEFAULT_LOCALE
        scope: RUN_TIME
        value: uk
      - key: SUPPORTED_LOCALES
        scope: RUN_TIME
        value: uk,en
      - key: SKIP_ENV_VALIDATION
        scope: BUILD_TIME
        value: "true"
    alert_policy:
      rule: DEPLOYMENT_FAILED
      disabled: false

databases:
  - name: db
    engine: PG
    version: "15"
    production: true
    cluster_name: centerplus-db
    db_name: centerplus
    db_user: centerplus_user
    db_size: db-s-dev-plus
    num_nodes: 1
    region: fra