apiVersion: v1
kind: Service
metadata:
  name: kafka-controller
  labels:
    app: kafka-controller
spec:
  ports:
  - port: 9093
    name: plaintext
  clusterIP: None
  selector:
    app: kafka-controller
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-controller
spec:
  selector:
    matchLabels:
      app: kafka-controller
  serviceName: "kafka-controller"
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-controller
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka-controller
        image: apache/kafka:latest
        env:
        - name: CLUSTER_ID
          value: "ee0afe51-046d-416d-b95e-da7c4c635284"
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: controller
        - name: KAFKA_LISTENERS
          value: CONTROLLER://:9093
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-controller-0.kafka-controller.dev.svc.cluster.local:9093"
        ports:
        - containerPort: 9093
          name: plaintext
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: kafka-controller-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: cstor-csi
      resources:
        requests:
          storage: 5Gi
